server:
  port: 2001
spring:
  application:
    name: MOVIES
    
  h2:
    console:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
